# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: fa871d34f8af7d81451855c2dd7e716b11d76e5ac1da7a35951020fb75416ee03b4c545f020a03f698a1ba17efb4f3822bef13e9f95f08fc7222d7dcf7e1ab9a

test:
  secret_key_base: b30835834f71fefe557e16aa7704de0cbd747191347544f3df0950f16d2dfcbaa05f71d2118b581586ad1d55ec4940424a536630b18ace698d04d36822a70b62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
